name: HELLO-WORK-FLOW
on:
    push:
        branches-ignore:
            - 'dependabot/**'
    pull_request:
        types: [closed, opened, synchronize, reopened]
        branches:
            - '*'
permissions:
    contents: read

jobs:
    generator-unit-tests:
        if: >-
            github.event.action != 'closed'
        runs-on: ubuntu-20.04
        timeout-minutes: 20
        strategy:
            fail-fast: false
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - uses: actions/checkout@v3
            - name: 'print-out-date'
              run: echo ${{ steps.date.outputs.date }}
            - run: git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit
              shell: bash
            - run: pwd
            - run: echo HELLO
    applications:
        name: ${{ matrix.itegration-apps}}
        runs-on: ${{ matrix.os || 'ubuntu-20.04' }}
        needs: generator-unit-tests
        strategy:
            matrix:
                itegration-test-apps: [ngx-jwt, ngx-oauth2]
        steps:
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - name: 'print-application name'
              run: echo ${{ matrix.itegration-test-apps }}
            - name: 'print date'
              run: echo $ {{ steps.date.outputs.date }}
